### ISSUE TITLE
Cluster launched, SSH'd into master, no kubeconfig or kubeconfig_ip found.

### ISSUE THREAD

**Issue by guydavis** [scholzj/aws-kubernetes#6]
Thanks for this!  Where else should I check for issues with the deployment?  I launch the cluster with terraform but on SSH'ing into the master node, neither file is found:
* /home/centos/kubeconfig
* /home/centos/kubeconfig_ip

Don't see anything clearly wrong in [cloud-init.log](https://github.com/scholzj/aws-kubernetes/files/2706520/cloud-init.log)

**Comment by scholzj** [comment]
Which version are you using? The latest one should be writing additional log file to `/var/log/init-aws-kubernetes-master.log` (on the master node) or `/var/log/init-aws-kubernetes-node.log` (on the worker nodes). Can you have a look at them and share their content?

**Comment by guydavis** [comment]
Thanks much!  The two logs above told the tale, turned out to be misconfigured DNS/DHCP on our VPC, leading to failed name resolution.  I've worked around it.  Thanks again for the great Terraform & Kubernetes deployment.
