### ISSUE TITLE
Error: no matching Route53Zone found 

### ISSUE THREAD

**Issue by keremceliker** [scholzj/aws-kubernetes#7]
Hello,

When i run the terraform apply cli as the follows below, im getting issue as the follows. 
I'm actually new learner by the way, how can i fix this with simply-way ? I just wanted to learn and run on aws with your kindly support

C:\Users\andromeda\26042020_Test>terraform apply --var-file example.tfvars
module.kubernetes.data.template_file.node_policy_json: Refreshing state...
module.kubernetes.data.template_file.master_policy_json: Refreshing state...
module.kubernetes.data.template_file.cloud_init_config: Refreshing state...
module.kubernetes.data.aws_subnet.cluster_subnet: Refreshing state...
module.kubernetes.data.aws_route53_zone.dns_zone: Refreshing state...
module.kubernetes.data.aws_ami.centos7: Refreshing state...

Error: no matching Route53Zone found

  on .terraform\modules\kubernetes\terraform-aws-kubernetes-1.10.1\main.tf line 415, in data "aws_route53_zone" "dns_zone":
 415: data "aws_route53_zone" "dns_zone" {

**Comment by scholzj** [comment]
You need to specify a DNS Zone configuried in AWS Route53. If you don't have any domains in Route53, you should be able to create a private DNS zone. You will nto be able to really use the DNS names - only IPs, but it should work IIRC.

**Comment by scholzj** [comment]
(it is configured using the `hosted_zone` and `hosted_zone_private` options)
